apiVersion: apps/v1
kind: Deployment
metadata:
  name: asgbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secopsbuggy
  template:
    metadata:
      labels:
        app: secopsbuggy
    spec:
      containers:
      - name: secopsbuggy
        image: 624284600553.dkr.ecr.us-west-2.amazonaws.com/secops
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: secopsbuggy
    k8s-app: secopsbuggy
  name: secopsbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: secopsbuggy
